name: Release

on:
  push:
    branches:
      - trunk

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set Docker image name
        run: echo "IMAGE_TAG=app-artifact-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Configurar Docker
        run: |
          echo "Simulando login a ECR"
          echo "Simulando docker build"
          docker build -t health-check-service:$IMAGE_TAG .

      - name: Simular push
        run: |
          echo "Simulando push a ECR"
          echo "docker tag health-check-service:$IMAGE_TAG fake-ecr-url/health-check-service:$IMAGE_TAG"
          echo "docker push fake-ecr-url/health-check-service:$IMAGE_TAG"

      - name: Simular despliegue a ECS
        run: |
          echo "Simulando deploy a ECS"
          echo "aws ecs update-service --cluster fake-cluster --service fake-service --force-new-deployment"