name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: |
          echo "Simulando login a ECR"
          echo "Simulando docker build"
          docker build -t health-check-service:latest .

      - name: Simular push
        run: |
          echo "Simulando push a ECR"
          echo "docker tag health-check-service:latest fake-ecr-url/health-check-service:latest"
          echo "docker push fake-ecr-url/health-check-service:latest"

      - name: Simular despliegue a ECS
        run: |
          echo "Simulando deploy a ECS"
          echo "aws ecs update-service --cluster fake-cluster --service fake-service --force-new-deployment"